START TRANSACTION;
CREATE TABLE waifupendingpayout (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid numeric(20,0) NOT NULL,
    amount numeric NOT NULL,
    CONSTRAINT pk_waifupendingpayout PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_waifupendingpayout_userid ON waifupendingpayout (userid);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260311220657_add-waifu-pending-payout', '9.0.1');

COMMIT;

