START TRANSACTION;

-- ============================================================
-- STEP 0: Save old waifu data before destructive schema changes
-- ============================================================

CREATE TEMP TABLE _old_waifus AS
SELECT wi.id AS old_id, du_waifu.userid AS discord_user_id, wi.price AS old_price,
       du_claimer.userid AS claimer_discord_user_id, du_affinity.userid AS affinity_discord_user_id
FROM waifuinfo wi
INNER JOIN discorduser du_waifu ON du_waifu.id = wi.waifuid
LEFT JOIN discorduser du_claimer ON du_claimer.id = wi.claimerid
LEFT JOIN discorduser du_affinity ON du_affinity.id = wi.affinityid;

CREATE TEMP TABLE _old_gifts AS
SELECT du_waifu.userid AS waifu_discord_user_id, LOWER(item.name) AS item_name, COUNT(*) AS cnt
FROM waifuitem item
INNER JOIN waifuinfo wi ON wi.id = item.waifuinfoid
INNER JOIN discorduser du_waifu ON du_waifu.id = wi.waifuid
GROUP BY du_waifu.userid, LOWER(item.name);

-- ============================================================
-- STEP 1: Auto-generated schema migration (from EF Core)
-- ============================================================

ALTER TABLE waifuinfo DROP CONSTRAINT fk_waifuinfo_discorduser_affinityid;

ALTER TABLE waifuinfo DROP CONSTRAINT fk_waifuinfo_discorduser_claimerid;

ALTER TABLE waifuinfo DROP CONSTRAINT fk_waifuinfo_discorduser_waifuid;

DROP TABLE waifuitem;

DROP TABLE waifuupdates;

DROP INDEX ix_waifuinfo_affinityid;

DROP INDEX ix_waifuinfo_claimerid;

DROP INDEX ix_waifuinfo_price;

DROP INDEX ix_waifuinfo_waifuid;

ALTER TABLE waifuinfo DROP COLUMN affinityid;

ALTER TABLE waifuinfo DROP COLUMN claimerid;

ALTER TABLE waifuinfo DROP COLUMN dateadded;

ALTER TABLE waifuinfo RENAME COLUMN waifuid TO waifufeepercent;

ALTER TABLE waifuinfo ADD customavatarurl text;

ALTER TABLE waifuinfo ADD description text;

ALTER TABLE waifuinfo ADD food integer NOT NULL DEFAULT 0;

ALTER TABLE waifuinfo ADD ishubby boolean NOT NULL DEFAULT FALSE;

ALTER TABLE waifuinfo ADD lastdecaytime timestamp without time zone NOT NULL DEFAULT TIMESTAMP '-infinity';

ALTER TABLE waifuinfo ADD manageruserid numeric(20,0);

ALTER TABLE waifuinfo ADD mood integer NOT NULL DEFAULT 0;

ALTER TABLE waifuinfo ADD quote text;

ALTER TABLE waifuinfo ADD returnscap bigint NOT NULL DEFAULT 0;

ALTER TABLE waifuinfo ADD totalproduced bigint NOT NULL DEFAULT 0;

ALTER TABLE waifuinfo ADD userid numeric(20,0) NOT NULL DEFAULT 0.0;

ALTER TABLE userquest ALTER COLUMN progress TYPE bigint;

CREATE TABLE channelspotoverride (
    channelid numeric(20,0) NOT NULL,
    spot integer NOT NULL,
    CONSTRAINT pk_channelspotoverride PRIMARY KEY (channelid)
);

CREATE TABLE lineupuser (
    guildid numeric(20,0) NOT NULL,
    channelid numeric(20,0) NOT NULL,
    userid numeric(20,0) NOT NULL,
    reason character varying(200),
    dateadded timestamp without time zone NOT NULL,
    CONSTRAINT pk_lineupuser PRIMARY KEY (guildid, channelid, userid)
);

CREATE TABLE waifucycle (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    waifuuserid numeric(20,0) NOT NULL,
    cyclenumber integer NOT NULL,
    manageruserid numeric(20,0) NOT NULL,
    totalbacked bigint NOT NULL,
    totalreturns bigint NOT NULL,
    waifuearnings bigint NOT NULL,
    managerearnings bigint NOT NULL,
    fanpool bigint NOT NULL,
    moodsnapshot integer NOT NULL,
    foodsnapshot integer NOT NULL,
    processedat timestamp without time zone NOT NULL,
    CONSTRAINT pk_waifucycle PRIMARY KEY (id)
);

CREATE TABLE waifucyclesnapshot (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    cyclenumber integer NOT NULL,
    waifuuserid numeric(20,0) NOT NULL,
    userid numeric(20,0) NOT NULL,
    snapshotbalance bigint NOT NULL,
    CONSTRAINT pk_waifucyclesnapshot PRIMARY KEY (id)
);

CREATE TABLE waifufan (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    userid numeric(20,0) NOT NULL,
    waifuuserid numeric(20,0) NOT NULL,
    delegatedat timestamp without time zone NOT NULL,
    leftat timestamp without time zone,
    CONSTRAINT pk_waifufan PRIMARY KEY (id)
);

CREATE TABLE waifugiftcount (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    waifuuserid numeric(20,0) NOT NULL,
    giftitemid uuid NOT NULL,
    count integer NOT NULL,
    CONSTRAINT pk_waifugiftcount PRIMARY KEY (id)
);

-- Clear all rows before unique index (data is saved in _old_waifus)
DELETE FROM waifuinfo;

CREATE UNIQUE INDEX ix_waifuinfo_userid ON waifuinfo (userid);

CREATE INDEX ix_lineupuser_guildid_channelid_dateadded ON lineupuser (guildid, channelid, dateadded);

CREATE INDEX ix_lineupuser_guildid_channelid_userid ON lineupuser (guildid, channelid, userid);

CREATE UNIQUE INDEX ix_waifucycle_waifuuserid_cyclenumber ON waifucycle (waifuuserid, cyclenumber);

CREATE INDEX ix_waifucyclesnapshot_cyclenumber_waifuuserid ON waifucyclesnapshot (cyclenumber, waifuuserid);

CREATE UNIQUE INDEX ix_waifucyclesnapshot_cyclenumber_waifuuserid_userid ON waifucyclesnapshot (cyclenumber, waifuuserid, userid);

CREATE UNIQUE INDEX ix_waifufan_userid ON waifufan (userid);

CREATE INDEX ix_waifufan_waifuuserid ON waifufan (waifuuserid);

CREATE UNIQUE INDEX ix_waifugiftcount_waifuuserid_giftitemid ON waifugiftcount (waifuuserid, giftitemid);

-- ============================================================
-- STEP 2: Restore migrated waifu data
-- ============================================================

-- Clear junk rows left by the column renames (old waifuid values in waifufeepercent, etc.)
DELETE FROM waifuinfo;

-- Insert migrated waifus with correct column values
INSERT INTO waifuinfo (userid, mood, food, waifufeepercent, price, manageruserid,
                       returnscap, ishubby, lastdecaytime, totalproduced)
SELECT discord_user_id, 500, 500, 5, old_price, claimer_discord_user_id,
       1000000, FALSE, now() AT TIME ZONE 'UTC', 0
FROM _old_waifus;

-- Insert gift counts with name-to-UUID mapping
INSERT INTO waifugiftcount (waifuuserid, giftitemid, count)
SELECT waifu_discord_user_id,
    CASE item_name
        WHEN 'cookie'     THEN '019479a1-0001-7000-8000-000000000001'::uuid
        WHEN 'donut'      THEN '019479a1-0002-7000-8000-000000000002'::uuid
        WHEN 'bread'      THEN '019479a1-0003-7000-8000-000000000003'::uuid
        WHEN 'onigiri'    THEN '019479a1-0004-7000-8000-000000000004'::uuid
        WHEN 'pizza'      THEN '019479a1-0005-7000-8000-000000000005'::uuid
        WHEN 'burger'     THEN '019479a1-0006-7000-8000-000000000006'::uuid
        WHEN 'bento'      THEN '019479a1-0007-7000-8000-000000000007'::uuid
        WHEN 'pasta'      THEN '019479a1-0008-7000-8000-000000000008'::uuid
        WHEN 'cake'       THEN '019479a1-0009-7000-8000-000000000009'::uuid
        WHEN 'sushi'      THEN '019479a1-000a-7000-8000-000000000010'::uuid
        WHEN 'lobster'    THEN '019479a1-000b-7000-8000-000000000011'::uuid
        WHEN 'feast'      THEN '019479a1-000c-7000-8000-000000000012'::uuid
        WHEN 'flower'     THEN '019479a1-1001-7000-8000-000000000101'::uuid
        WHEN 'ribbon'     THEN '019479a1-1002-7000-8000-000000000102'::uuid
        WHEN 'rose'       THEN '019479a1-1003-7000-8000-000000000103'::uuid
        WHEN 'loveletter' THEN '019479a1-1004-7000-8000-000000000104'::uuid
        WHEN 'teddy'      THEN '019479a1-1005-7000-8000-000000000105'::uuid
        WHEN 'gift'       THEN '019479a1-1006-7000-8000-000000000106'::uuid
        WHEN 'diamond'    THEN '019479a1-1007-7000-8000-000000000107'::uuid
        WHEN 'dress'      THEN '019479a1-1008-7000-8000-000000000108'::uuid
        WHEN 'piano'      THEN '019479a1-1009-7000-8000-000000000109'::uuid
        WHEN 'kitten'     THEN '019479a1-100a-7000-8000-000000000110'::uuid
        WHEN 'house'      THEN '019479a1-100b-7000-8000-000000000111'::uuid
        WHEN 'moon'       THEN '019479a1-100c-7000-8000-000000000112'::uuid
    END,
    cnt
FROM _old_gifts
WHERE item_name IN (
    'cookie', 'donut', 'bread', 'onigiri', 'pizza', 'burger',
    'bento', 'pasta', 'cake', 'sushi', 'lobster', 'feast',
    'flower', 'ribbon', 'rose', 'loveletter', 'teddy', 'gift',
    'diamond', 'dress', 'piano', 'kitten', 'house', 'moon'
);

-- Merge unmapped gift items into a single Legacy gift per waifu
INSERT INTO waifugiftcount (waifuuserid, giftitemid, count)
SELECT waifu_discord_user_id, '019479a1-ffff-7000-8000-ffffffffffff'::uuid, SUM(cnt)
FROM _old_gifts
WHERE item_name NOT IN (
    'cookie', 'donut', 'bread', 'onigiri', 'pizza', 'burger',
    'bento', 'pasta', 'cake', 'sushi', 'lobster', 'feast',
    'flower', 'ribbon', 'rose', 'loveletter', 'teddy', 'gift',
    'diamond', 'dress', 'piano', 'kitten', 'house', 'moon'
)
GROUP BY waifu_discord_user_id;

-- Migrate affinity relationships as fan records
-- discord_user_id = the fan (the user who set affinity)
-- affinity_discord_user_id = the waifu they're a fan of
INSERT INTO waifufan (userid, waifuuserid, delegatedat)
SELECT ow.discord_user_id, ow.affinity_discord_user_id, now() AT TIME ZONE 'UTC'
FROM _old_waifus ow
WHERE ow.affinity_discord_user_id IS NOT NULL
AND EXISTS (SELECT 1 FROM _old_waifus w2 WHERE w2.discord_user_id = ow.affinity_discord_user_id);

DROP TABLE _old_waifus;
DROP TABLE _old_gifts;

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20260308192116_waifu-rework', '9.0.1');

COMMIT;

