START TRANSACTION;

CREATE TABLE IF NOT EXISTS "autoflows" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "pk_autoflows" PRIMARY KEY,
    "dateadded" TIMESTAMP WITHOUT TIME ZONE NULL,
    "guildid" NUMERIC(20,0) NOT NULL,
    "name" TEXT NULL,
    "flowjson" TEXT NULL,
    "isenabled" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS "ix_autoflows_guildid" ON "autoflows" ("guildid");

CREATE TABLE IF NOT EXISTS "channelprefixes" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "pk_channelprefixes" PRIMARY KEY,
    "dateadded" TIMESTAMP WITHOUT TIME ZONE NULL,
    "guildid" NUMERIC(20,0) NOT NULL,
    "channelid" NUMERIC(20,0) NOT NULL,
    "prefix" TEXT NULL
);

CREATE INDEX IF NOT EXISTS "ix_channelprefixes_guildid" ON "channelprefixes" ("guildid");

CREATE TABLE IF NOT EXISTS "customscripts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "pk_customscripts" PRIMARY KEY,
    "dateadded" TIMESTAMP WITHOUT TIME ZONE NULL,
    "guildid" NUMERIC(20,0) NOT NULL,
    "trigger" TEXT NULL,
    "script" TEXT NULL,
    "isenabled" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS "ix_customscripts_guildid" ON "customscripts" ("guildid");

COMMIT;
