-- Pet Companions
CREATE TABLE IF NOT EXISTS "Pets" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" BIGINT NOT NULL,
    "GuildId" BIGINT NOT NULL,
    "Name" TEXT NOT NULL DEFAULT '',
    "Species" TEXT NOT NULL DEFAULT 'Dog',
    "Emoji" TEXT NOT NULL DEFAULT '🐶',
    "Level" INTEGER NOT NULL DEFAULT 1,
    "Xp" BIGINT NOT NULL DEFAULT 0,
    "Happiness" INTEGER NOT NULL DEFAULT 50,
    "Hunger" INTEGER NOT NULL DEFAULT 50,
    "Energy" INTEGER NOT NULL DEFAULT 100,
    "IsShiny" BOOLEAN NOT NULL DEFAULT FALSE,
    "Strength" INTEGER NOT NULL DEFAULT 0,
    "Agility" INTEGER NOT NULL DEFAULT 0,
    "Intelligence" INTEGER NOT NULL DEFAULT 0,
    "AdventureCount" INTEGER NOT NULL DEFAULT 0,
    "BattlesWon" INTEGER NOT NULL DEFAULT 0,
    "LastFedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "LastPlayedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    "EvolutionStage" INTEGER NOT NULL DEFAULT 1,
    "DateAdded" TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX IF NOT EXISTS "IX_Pets_UserId_GuildId" ON "Pets" ("UserId", "GuildId");
