-- Pet Companions
CREATE TABLE IF NOT EXISTS Pets (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER NOT NULL,
    GuildId INTEGER NOT NULL,
    Name TEXT NOT NULL DEFAULT '',
    Species TEXT NOT NULL DEFAULT 'Dog',
    Emoji TEXT NOT NULL DEFAULT '🐶',
    Level INTEGER NOT NULL DEFAULT 1,
    Xp INTEGER NOT NULL DEFAULT 0,
    Happiness INTEGER NOT NULL DEFAULT 50,
    Hunger INTEGER NOT NULL DEFAULT 50,
    Energy INTEGER NOT NULL DEFAULT 100,
    IsShiny INTEGER NOT NULL DEFAULT 0,
    Strength INTEGER NOT NULL DEFAULT 0,
    Agility INTEGER NOT NULL DEFAULT 0,
    Intelligence INTEGER NOT NULL DEFAULT 0,
    AdventureCount INTEGER NOT NULL DEFAULT 0,
    BattlesWon INTEGER NOT NULL DEFAULT 0,
    LastFedAt TEXT NOT NULL DEFAULT (datetime('now')),
    LastPlayedAt TEXT NOT NULL DEFAULT (datetime('now')),
    EvolutionStage INTEGER NOT NULL DEFAULT 1,
    DateAdded TEXT
);

CREATE INDEX IF NOT EXISTS IX_Pets_UserId_GuildId ON Pets (UserId, GuildId);
